[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "opencplc"
version = "0.4.8"
description = "Project configuration and build tool for OpenCPLC"
readme = "readme.md"
license = "MIT"
license-files = ["license"]
requires-python = ">=3.12"
authors = [{name = "Xaeian"}]
keywords = ["embedded", "stm32", "opencplc", "build", "forge"]
dependencies = ["xaeian>=1.0.1", "packaging"]

[project.scripts]
opencplc = "opencplc.__main__:main"

[project.urls]
Repository = "https://github.com/OpenCPLC/Forge"

[tool.setuptools.packages.find]
include = ["opencplc*"]

[tool.setuptools.package-data]
opencplc = ["files/**"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_functions = ["*"]
