# Generated by OpenCPLC Forge, reload with opencplc -r

NAME := ${NAME}
TARGET := ${TARGET}

# Paths anchored to this file, so make -C works from any directory
THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
MAKEFILE_PATH := $(abspath $(THIS_MAKEFILE))
PROJECT := $(patsubst %/,%,$(dir $(MAKEFILE_PATH)))
WORKSPACE := $(abspath $(PROJECT)/${UP_PATH})
OPENCPLC := $(WORKSPACE)/${CORE_DIR}
BUILD := $(WORKSPACE)/${BUILD_DIR}

# Platform defines and program extension come from Make, same file on Windows and Linux
ifeq ($(OS),Windows_NT)
SHELL := cmd.exe
.SHELLFLAGS := /c
MKDIR = if not exist "$(subst /,\,$1)" mkdir "$(subst /,\,$1)"
RMDIR = if exist "$(subst /,\,$1)" rmdir /s /q "$(subst /,\,$1)"
COPY = copy /y "$(subst /,\,$1)" "$(subst /,\,$2)" >nul
C_DEFS = -DHOST -D_WIN64
LIBS = -lm -lbcrypt
EXE = $(BUILD)/$(TARGET).exe
else
SHELL := /bin/sh
MKDIR = mkdir -p $1
RMDIR = rm -rf $1
COPY = cp $1 $2
C_DEFS = -DHOST -D_GNU_SOURCE
LIBS = -lm -lpthread
EXE = $(BUILD)/$(TARGET)
endif

# Core sources, relative to $(OPENCPLC)
CORE_C = ${CORE_C}

# Project sources, relative to $(PROJECT)
PRO_C = ${PRO_C}

C_INCLUDES = ${C_INCLUDES}

CC = gcc
OPT = -${OPT_LEVEL}

CFLAGS = -std=c11 $(OPT) -Wall -Wextra $(C_DEFS) $(C_INCLUDES)
CFLAGS += -g -MMD -MP -MF"$(@:%.o=%.d)"

# Core (opencplc/) and project objects in separate trees, named after full source paths;
# outputs sit next to them
OBJECTS := $(patsubst %.c,$(BUILD)/opencplc/%.o,$(CORE_C))
OBJECTS += $(patsubst %.c,$(BUILD)/project/%.o,$(PRO_C))

CONFIG_DEPS = $(PROJECT)/main.h $(MAKEFILE_PATH)

# Configuration changed: Forge rewrites this file and Make restarts once with fresh sources
FORGE = opencplc
CONFIG_INPUTS = $(wildcard ${CONFIG_INPUTS})

$(THIS_MAKEFILE): $(CONFIG_INPUTS)
	@cd $(WORKSPACE) && $(FORGE) -r $(NAME)

.DEFAULT_GOAL := build

$(BUILD)/opencplc/%.o: $(OPENCPLC)/%.c $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD)/project/%.o: $(PROJECT)/%.c $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(CC) -c $(CFLAGS) $< -o $@

$(EXE): $(OBJECTS)
		$(CC) $(OBJECTS) $(LIBS) -o $@

build: $(EXE)

run: build
	$(EXE)

# make dist TAG=1.2.0 names the copy <target>-1.2.0
DIST := $(TARGET)$(if $(TAG),-$(TAG))$(suffix $(EXE))

dist: build
	@$(call COPY,$(EXE),$(PROJECT)/$(DIST))
	@echo Copied ${GREEN}$(DIST)${END} to ${PROJECT_COLORED}

clean:
	@$(call RMDIR,$(BUILD))
	@echo Removed ${BUILD_COLORED}

clr: clean

.PHONY: build run dist clean clr

-include $(OBJECTS:.o=.d)
