# Generated by OpenCPLC Forge, reload with `opencplc -r`

NAME := ${NAME}
TARGET := ${TARGET}
STLINK := ${STLINK}
FLASH_kB := ${FLASH}
RAM_kB := ${RAM}
BOOT := ${BOOT}

# Paths anchored to this file, so `make -C` works from any directory
THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
MAKEFILE_PATH := $(abspath $(THIS_MAKEFILE))
PROJECT := $(patsubst %/,%,$(dir $(MAKEFILE_PATH)))
WORKSPACE := $(abspath $(PROJECT)/${UP_PATH})
OPENCPLC := $(WORKSPACE)/${CORE_DIR}
BUILD := $(WORKSPACE)/${BUILD_DIR}
# Bootloader packed in front of the image, empty without one
BOOT_IMAGE := ${BOOT_IMAGE}
# Where `dist` puts the flash image: the project, or Core for the bootloader with its elf
DIST_HEX = ${DIST_HEX}
DIST_ELF := ${DIST_ELF}
# `key` bootloader: where its key goes and the key `dist` signs with, both empty without one
BOOT_KEY_AT := ${BOOT_KEY_AT}
BOOT_KEY := ${BOOT_KEY}

ifeq ($(OS),Windows_NT)
SHELL := cmd.exe
.SHELLFLAGS := /c
# Forge packages first, so what the console has on `PATH` plays no part in a build
export PATH := ${TOOLS_PATH};$(PATH)
MKDIR = if not exist "$(subst /,\,$1)" mkdir "$(subst /,\,$1)"
RMDIR = if exist "$(subst /,\,$1)" rmdir /s /q "$(subst /,\,$1)"
COPY = copy /y "$(subst /,\,$1)" "$(subst /,\,$2)" >nul
TOUCH = type nul > "$(subst /,\,$1)"
else
SHELL := /bin/sh
MKDIR = mkdir -p $1
RMDIR = rm -rf $1
COPY = cp $1 $2
TOUCH = touch $1
endif

# Core sources, relative to `$(OPENCPLC)`
CORE_C = ${CORE_C}

CORE_S = ${CORE_S}

# Project sources, relative to `$(PROJECT)`
PRO_C = ${PRO_C}

PRO_S = ${PRO_S}

C_INCLUDES = ${C_INCLUDES}

PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

MCU = ${MCU_FLAGS}
C_DEFS = ${C_DEFS}
OPT = -${OPT_LEVEL}

ASFLAGS = $(MCU) $(C_DEFS) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS += -g -gdwarf-2 -MMD -MP -MF"$(@:%.o=%.d)"

LD_SCRIPT = $(PROJECT)/flash.ld
LIBS = -lc -lm -lnosys
LDFLAGS = $(MCU) -specs=nano.specs -T$(LD_SCRIPT) $(LIBS)
LDFLAGS += -Wl,--no-warn-rwx-segment,-Map=$(BUILD)/$(TARGET).map,--cref -Wl,--gc-sections

# Core (`opencplc/`) and project objects in separate trees, named after full source paths
# Outputs sit next to them
OBJECTS := $(patsubst %.c,$(BUILD)/opencplc/%.o,$(CORE_C))
OBJECTS += $(patsubst %.s,$(BUILD)/opencplc/%.o,$(CORE_S))
OBJECTS += $(patsubst %.c,$(BUILD)/project/%.o,$(PRO_C))
OBJECTS += $(patsubst %.s,$(BUILD)/project/%.o,$(PRO_S))

# Every object depends on the makefile, because a flag change touches all of them
# main.h is not listed: `-MMD -MP` records in the .d files which objects really include it
# Editing it rebuilds exactly those
CONFIG_DEPS = $(MAKEFILE_PATH)

# Configuration changed: Forge rewrites this file and Make restarts once with fresh sources
# Stamp carries the reload time, so a rewrite with identical content rebuilds nothing
FORGE = opencplc
CONFIG_INPUTS = $(wildcard ${CONFIG_INPUTS})
FORGE_STAMP := $(BUILD)/.forge

$(THIS_MAKEFILE): $(FORGE_STAMP) ;

$(FORGE_STAMP): $(CONFIG_INPUTS)
	@$(call MKDIR,$(BUILD))
	@cd $(WORKSPACE) && $(FORGE) -r $(NAME)
	@$(call TOUCH,$@)

.DEFAULT_GOAL := build

$(BUILD)/opencplc/%.o: $(OPENCPLC)/%.c $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD)/opencplc/%.o: $(OPENCPLC)/%.s $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD)/project/%.o: $(PROJECT)/%.c $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD)/project/%.o: $(PROJECT)/%.s $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD)/$(TARGET).elf: $(OBJECTS) $(LD_SCRIPT)
		$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@
	@cd $(WORKSPACE) && $(FORGE) -z $@ $(FLASH_kB) $(RAM_kB)

$(BUILD)/%.hex: $(BUILD)/%.elf
	$(HEX) $< $@

$(BUILD)/%.bin: $(BUILD)/%.elf
	$(BIN) $< $@

# Whole flash in one file for the programmer
# Under the bootloader: bootloader in front, CRC in the trailer, update binary beside
# Under the `key` one the development key signs the image and goes into the bootloader
# New bootloader in Core packs again, without a clean
$(BUILD)/$(TARGET)-dist.hex: $(BUILD)/$(TARGET).hex $(BOOT_IMAGE)
	@cd $(WORKSPACE) && $(FORGE) --pack $< $@ $(BOOT_IMAGE) $(BOOT_KEY_AT)

ARTIFACTS := $(BUILD)/$(TARGET).elf $(BUILD)/$(TARGET).hex $(BUILD)/$(TARGET).bin \
  $(BUILD)/$(TARGET)-dist.hex

# Only top make with `build` as its goal says it
# Run in the project that is this one, under the dispatcher that one, behind `dist` nobody
ifeq ($(MAKELEVEL),0)
ifeq ($(filter-out build,$(MAKECMDGOALS)),)
BUILD_SAYS := yes
endif
endif

ifeq ($(BUILD_SAYS),yes)
build:
	@"$(MAKE)" --no-print-directory -q $(ARTIFACTS) && echo Nothing to be done for ${GOLD}build${END}|| "$(MAKE)" --no-print-directory $(ARTIFACTS)
else
build: $(ARTIFACTS)
endif

# ST-Link, the pinned probe, the chip held in reset: the same openocd `--program` runs
OPENOCD = ${OPENOCD} -c

# One file with or without a bootloader, `--pack` already put it in front
# Looked for when `flash` runs, so `make run` finds the image its build just made
flash:
	@$(if $(wildcard $(BUILD)/$(TARGET)-dist.hex),$(OPENOCD) "program $(BUILD)/$(TARGET)-dist.hex verify reset exit" && echo Flashed ${LIME}$(TARGET)-dist.hex${END}|| (echo Flashing ${RED}failed${END}&& exit 1),echo No image ${LIME}$(TARGET)-dist.hex${END} to flash, build it with make)

run: build flash

erase:
	@$(OPENOCD) "init; reset init; ${ERASE_CMD}; reset halt; exit" && echo Erased ${PINK}${CHIP}${END}|| (echo Erasing ${RED}failed${END}&& exit 1)

# Radio stack of CPU2: `FUS=1` provisions a factory board, `FAST=1` trusts the installed one
stack: export PATH := ${CUBE_PATH};$(PATH)
stack:
	@${STACK_CMD}

# `make dist TAG=1.2.0` gives <target>-1.2.0.hex, the flash image for a programmer
# Under the bootloader the hex is the full image, <target>-1.2.0.bin the image alone for an update
# Packed again rather than copied: under the `key` bootloader `PRO_BOOT_KEY` signs, not the build
# Stamp touched, so a new file in the project does not force a reload on the next make
DIST := $(TARGET)$(if $(TAG),-$(TAG))

dist: build
	@cd $(WORKSPACE) && $(FORGE) --pack $(BUILD)/$(TARGET).hex $(DIST_HEX) $(BOOT_IMAGE) $(BOOT_KEY_AT) $(BOOT_KEY)
ifneq ($(DIST_ELF),)
	@$(call COPY,$(BUILD)/$(TARGET).elf,$(DIST_ELF))
	@echo Bootloader ${LIME}$(notdir $(DIST_HEX))${END} and ${VIOLET}$(notdir $(DIST_ELF))${END} to Core
else ifeq ($(BOOT),true)
	@echo Full image ${LIME}$(DIST).hex${END} to ${PROJECT_COLORED}
	@echo Update image ${SKY}$(DIST).bin${END} to ${PROJECT_COLORED}
else
	@echo Flash image ${LIME}$(DIST).hex${END} to ${PROJECT_COLORED}
endif
	@$(call TOUCH,$(FORGE_STAMP))

clean:
	@$(call RMDIR,$(BUILD))
	@echo Removed ${BUILD_COLORED}

clr: clean

.PHONY: build run flash erase stack dist clean clr

-include $(OBJECTS:.o=.d)
