# Generated by OpenCPLC Forge, reload with opencplc -r

NAME := ${NAME}
TARGET := ${TARGET}
STLINK := ${STLINK}
FLASH_kB := ${FLASH}
RAM_kB := ${RAM}

# Paths anchored to this file, so make -C works from any directory
THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
MAKEFILE_PATH := $(abspath $(THIS_MAKEFILE))
PROJECT := $(patsubst %/,%,$(dir $(MAKEFILE_PATH)))
WORKSPACE := $(abspath $(PROJECT)/${UP_PATH})
OPENCPLC := $(WORKSPACE)/${CORE_DIR}
BUILD := $(WORKSPACE)/${BUILD_DIR}

ifeq ($(OS),Windows_NT)
SHELL := cmd.exe
.SHELLFLAGS := /c
MKDIR = if not exist "$(subst /,\,$1)" mkdir "$(subst /,\,$1)"
RMDIR = if exist "$(subst /,\,$1)" rmdir /s /q "$(subst /,\,$1)"
COPY = copy /y "$(subst /,\,$1)" "$(subst /,\,$2)" >nul
else
SHELL := /bin/sh
MKDIR = mkdir -p $1
RMDIR = rm -rf $1
COPY = cp $1 $2
endif

# Core sources, relative to $(OPENCPLC)
CORE_C = ${CORE_C}

CORE_S = ${CORE_S}

# Project sources, relative to $(PROJECT)
PRO_C = ${PRO_C}

PRO_S = ${PRO_S}

C_INCLUDES = ${C_INCLUDES}

PREFIX = arm-none-eabi-
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

MCU = ${MCU_FLAGS}
C_DEFS = ${C_DEFS}
OPT = -${OPT_LEVEL}

ASFLAGS = $(MCU) $(C_DEFS) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CFLAGS += -g -gdwarf-2 -MMD -MP -MF"$(@:%.o=%.d)"

LD_SCRIPT = $(PROJECT)/flash.ld
LIBS = -lc -lm -lnosys
LDFLAGS = $(MCU) -specs=nano.specs -T$(LD_SCRIPT) $(LIBS)
LDFLAGS += -Wl,--no-warn-rwx-segment,-Map=$(BUILD)/$(TARGET).map,--cref -Wl,--gc-sections

# Core (opencplc/) and project objects in separate trees, named after full source paths;
# outputs sit next to them
OBJECTS := $(patsubst %.c,$(BUILD)/opencplc/%.o,$(CORE_C))
OBJECTS += $(patsubst %.s,$(BUILD)/opencplc/%.o,$(CORE_S))
OBJECTS += $(patsubst %.c,$(BUILD)/project/%.o,$(PRO_C))
OBJECTS += $(patsubst %.s,$(BUILD)/project/%.o,$(PRO_S))

CONFIG_DEPS = $(PROJECT)/main.h $(MAKEFILE_PATH)

# Configuration changed: Forge rewrites this file and Make restarts once with fresh sources
FORGE = opencplc
CONFIG_INPUTS = $(wildcard ${CONFIG_INPUTS})

$(THIS_MAKEFILE): $(CONFIG_INPUTS)
	@cd $(WORKSPACE) && $(FORGE) -r $(NAME)

.DEFAULT_GOAL := build

$(BUILD)/opencplc/%.o: $(OPENCPLC)/%.c $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD)/opencplc/%.o: $(OPENCPLC)/%.s $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD)/project/%.o: $(PROJECT)/%.c $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD)/project/%.o: $(PROJECT)/%.s $(CONFIG_DEPS)
	@$(call MKDIR,$(patsubst %/,%,$(dir $@)))
	$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD)/$(TARGET).elf: $(OBJECTS) $(LD_SCRIPT)
		$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@
	@cd $(WORKSPACE) && $(FORGE) -z $@ $(FLASH_kB) $(RAM_kB)

$(BUILD)/%.hex: $(BUILD)/%.elf
	$(HEX) $< $@

$(BUILD)/%.bin: $(BUILD)/%.elf
	$(BIN) $< $@

build: $(BUILD)/$(TARGET).elf $(BUILD)/$(TARGET).hex $(BUILD)/$(TARGET).bin

ifneq ($(STLINK),)
OPENOCD_SERIAL = -c "adapter serial $(STLINK)"
endif
OPENOCD = openocd -f interface/stlink.cfg $(OPENOCD_SERIAL) -f target/${OPENOCD_TARGET}.cfg -c

flash:
	$(OPENOCD) "program $(BUILD)/$(TARGET).elf verify reset exit"
	@echo Flashed ${GOLD}$(TARGET).elf${END}

run: build flash

erase:
	$(OPENOCD) "init; halt; ${ERASE_CMD}; reset halt; exit"
	@echo Erased ${PINK}${CHIP}${END}

# make dist TAG=1.2.0 names the copy <target>-1.2.0.hex
DIST := $(TARGET)$(if $(TAG),-$(TAG))

dist: build
	@$(call COPY,$(BUILD)/$(TARGET).hex,$(PROJECT)/$(DIST).hex)
	@echo Copied ${GREEN}$(DIST).hex${END} to ${PROJECT_COLORED}

clean:
	@$(call RMDIR,$(BUILD))
	@echo Removed ${BUILD_COLORED}

clr: clean

.PHONY: build run flash erase dist clean clr

-include $(OBJECTS:.o=.d)
