# Generated by OpenCPLC Forge, builds the active project

ACTIVE := ${ACTIVE}

ifeq ($(OS),Windows_NT)
SHELL := cmd.exe
.SHELLFLAGS := /c
RMDIR = if exist "$(subst /,\,$1)" rmdir /s /q "$(subst /,\,$1)"
else
SHELL := /bin/sh
RMDIR = rm -rf $1
endif

.DEFAULT_GOAL := build

ifeq ($(ACTIVE),)
build run flash erase stack dist clean clr:
	$(error No active project, select one with: ${CMD}opencplc <name>${END})
else
build:
	@echo Entering directory: ${ACTIVE_COLORED}
	@$(MAKE) --no-print-directory -q -C $(ACTIVE) build && echo Nothing to be done for ${GOLD}build${END}|| $(MAKE) --no-print-directory -C $(ACTIVE) build || (echo ${ERR} Build failed in ${ACTIVE_COLORED}&& exit 1)

run flash erase stack dist clean clr:
	@echo Entering directory: ${ACTIVE_COLORED}
	@$(MAKE) --no-print-directory -C $(ACTIVE) $@
endif

clean_all:
	@$(call RMDIR,build/projects)
	@echo Removed ${GREY}./build/projects${END}

clr_all: clean_all

.PHONY: build run flash erase stack dist clean clr clean_all clr_all
